### ISSUE TITLE
Mercadolivre

### ISSUE THREAD

**Issue by fabianski7** [easylistbrasil/easylistbrasil#10]
### Quais sites está tendo problemas?
mercadolivre.com.br

### O que está acontecendo?
O script de rastreamento do google analytics está sendo carregado através da cdn do mercado livre.
https://http2.mlstatic.com/analytics/ga/mlb-ml-analytics.min.js

Sugestão:
`||http2.mlstatic.com/analytics/*$domain=mercadolivre.com.br`

### Lista de inscrições de filtros que está usando:
uBlock filters e Adguard

### Outros:

- Navegador: Firefox
- Bloqueador de anúncio: uBlock

**Comment by easylistbrasil** [comment]
pronto
