### ISSUE TITLE
Problema com o Recaptcha

### ISSUE THREAD

**Issue by carloshbcabral** [easylistbrasil/easylistbrasil#4]
### Quais sites está tendo problemas?
Recaptcha

### O que está acontecendo?
Se o Recaptcha não verificar de primeira, a lista impede a exibição das imagens para conferir se você é humano.

### outros:

- Navegador: Chrome 71
- Bloqueador de anúncio: Nano Adblocker

**Comment by easylistbrasil** [comment]
atualiza o filtro e verifica agora se funciona, se não, me fale o site que está com problema copiando a url e colando aqui.

**Comment by easylistbrasil** [comment]
acabei de testar aqui com o nano e esta funcionando, só atualizar. 
https://www.google.com/recaptcha/api2/demo
