### ISSUE TITLE
Caixas de publicidade em brasilescola.uol.com.br

### ISSUE THREAD

**Issue by ghost** [easylistbrasil/easylistbrasil#5]
Link de exemplo: https://brasilescola.uol.com.br/historiab/era-vargas.htm

Algumas caixas (vazias) de publicidade não estão sendo bloqueadas.

Estes são os filtros cosméticos (para Ublock Origin):

##.omnia-new-ads.f-esquerda.publicidade-content
##.grid-2 > div:nth-of-type(4)
##.conteudo-materia > div:nth-of-type(3)
###pub-flutuante-secao-1
###area-flutuante-secao-1

- Navegador: Google Chrome 77.0.3865.90
- Bloqueador de anúncio: uBlock Origin + Nano Defender

**Comment by ghost** [comment]
Use as listas do Adguard (o uBlock Origin ativa a `spa, por: AdGuard Spanish/Portuguese` por padrão).

 Eles bloqueiam tudo que notifico: https://github.com/AdguardTeam/AdguardFilters/issues/28892#issuecomment-540641419

**Comment by ghost** [comment]
Tem também ##.conteudo-materia > div:nth-of-type(4) e ##.grid-2 > div:nth-of-type(4) no link de exemplo https://brasilescola.uol.com.br/historiab/era-vargas.htm

**Comment by easylistbrasil** [comment]
Desculpe a demora, mas já subi uma atualização, espero que fique bom, lembrando que esse filtro é focado no adblock, se usa ublock origin recomendo mandar um issue para os colaborodores dos filtros ublock origin: https://github.com/uBlockOrigin/uAssets/issues
