### ISSUE TITLE
Problemas com o site wolframalpha.com

### ISSUE THREAD

**Issue by ghost** [easylistbrasil/easylistbrasil#6]
### Quais sites está tendo problemas?
wolframalpha.com

### O que está acontecendo?
o filtro cosmético ##[src*="data:image"] bloqueia imagens que não são publicidade, como o logotipo principal.
### Especificações:

- Navegador: Firefox 69.0.3
- Bloqueador de anúncio: uBlock Origin + Nano Defender

**Comment by easylistbrasil** [comment]
Já subi uma atualização removendo,  intenção dele era para sites de filmes que tinha imagens camufladas do imgid, mas como muitos desses sites já estão off, resolvi remover
