### ISSUE TITLE
Work together with portuguese list?

### ISSUE THREAD

**Issue by peace2000** [easylistbrasil/easylistbrasil#7]
Hi, I happened to find my way here through Easylist forums.

Is there specific need to have a separate blocking list for Brazil? As the main language of Brazil is portuguese that is spoken in other countries as well (for e.g: Portugal).

There is an existing portuguese list:
https://forums.lanik.us/viewforum.php?f=109
https://github.com/easylist/easylistportuguese

In my opinion you would do better together as you share the same language and the purpose of both lists is to block ads?

**Comment by easylistbrasil** [comment]
Well, I made this list, because the esylist community is very restricted to english, it barely has support for what you want and it still has the issue of pages being dynamic with anti-adblock. this filter breaks this mechanism in many cases, at least for me it is useful.
