### ISSUE TITLE
A lista bloqueia também cookies, scripts e elementos css usados em paywalls como as da Folha e G1?

### ISSUE THREAD

**Issue by fabiorzfreitas** [easylistbrasil/easylistbrasil#8]
Os elementos das paywalls são sempre ou códigos nas páginas, ou chamados para verificar cookies ou adblockers. Eu não sei exatamente como funciona, mas sei que o [Anti Adblock Killer](https://reek.github.io/anti-adblock-killer/) usa tanto um filtro de lista, quanto um script próprio então é possível que parte da funcionalidade possa ser usada na EasyList Brasil.

**Comment by easylistbrasil** [comment]
paywall bloqueia, agora pra cookies tem uma lista especifica pra isso: https://subscribe.adblockplus.org/?location=https%3A//www.i-dont-care-about-cookies.eu/abp/&title=I%20don%27t%20care%20about%20cookies
