### ISSUE TITLE
Server com Recaptcha

### ISSUE THREAD

**Issue by alkabane** [easylistbrasil/easylistbrasil#9]
### Quais sites está tendo problemas?

https://encurtaon.com
ex:
https://bibliotechsuper.com/Downloads/Downloads/

### O que está acontecendo?
recaptcha pede para desativar bloqueador , tem como bypass sem desativar?

### Lista de inscrições de filtros que está usando:
easylistbrasil

### outros:

- Navegador: Chrome
- Bloqueador de anúncio: Ublock Origin

Obrigado!

**Comment by easylistbrasil** [comment]
resolvido
